languageCode = "en"
languageName = "English"
weight = 1
title = "Utkarsh Deoli"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "nekonobg.png"
secondaryLogo = "neko.jpg"
description = "Hey! Welcome to my website!"

