[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "hqayMdRnS6"
weight = 1

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "hqayNdRnS6"
weight = 2

[[main]]
name = "Blog"
pageRef = "Blog"
identifier = "BL4vAxAMDP"
weight = 3

[[main]]
name = "Contact"
pageRef = "Contact"
url = "mailto:utkarsh.deoli+work@gmail.com"
identifier = "f4AK879oeK"
weight = 4

[[main]]
name = "Resume"
pageRef = "Resume"
url = "https://firebasestorage.googleapis.com/v0/b/utkarshdeolidev.appspot.com/o/UtkarshDeoli.pdf?alt=media"
identifier = "r4AK879oeK"
weight = 5

[[footer]]
none = "none"
