[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "hqayMdRnS6"
weight = 1

[[main]]
name = "Projects"
pageRef = ""
url = "https://whois.utkarshdeoli.in"
identifier = "hqayNdRnS6"
weight = 3

[[main]]
name = "Blog"
pageRef = "Blog"
identifier = "BL4vAxAMDP"
weight = 2

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "f4AK879oeK"
weight = 4

[[main]]
name = "Resume"
pageRef = "Resume"
url = "https://drive.google.com/file/d/1kKEtwNV-2PyuKQ4UnZEfO-AnTdn6Z4-s/view?usp=sharing"
identifier = "r4AK879oeK"
weight = 5

[[footer]]
none = "none"
