colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = false
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "image.jpg"
defaultFeaturedImage = "bk2.jpg"
highlightCurrentMenuArea = "enable"
mainSections = [ "blog", "projects" ]

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background" # valid options: page, profile, hero, card, background, custom
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/projects"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "back.gif"

[author]
name = "Utkarsh Deoli"
image = "profile.jpg"
headline = "Your Friendly Neighborhood Developer"
bio = "Just a developer for fun"
links = [ { envelope = "mailto:utkarsh.deoli@gmail.com?subject=Contacting%20from%20your%20website" }, { github = "https://github.com/UtkarshDeoli" }, { linkedin = "https://www.linkedin.com/in/utkarshdeoli" }, { x-twitter = "https://x.com/utkarshdeoli" }, { youtube = "https://www.youtube.com/@utkarshdeoli" } ,{ code = "https://www.leetcode.com/sagemodeutkarsh"}]


[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showZenMode = true

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = true
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyAd1UI7tCGyjupyyE_QiAY-DRKNR10l7S4"
authDomain = "utkarshdeolidev.firebaseapp.com"
projectId = "utkarshdeolidev"
storageBucket = "utkarshdeolidev.appspot.com"
messagingSenderId = "940345973759"
appId = "1:940345973759:web:28db2df19bba3d06f5e5ca"
measurementId = "G-YP0F0GC2D5"

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]

